DROP TABLE IF EXISTS blog_posts;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS plants;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
